

CREATE TABLE  `BRANDS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE  `PRODUCTS` (
  `ID` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE  `PRIORITY` (
  `ID` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`));

CREATE TABLE  `PRICES` (
  `BRAND_ID` INT NULL DEFAULT NULL,
  `PRODUCT_ID` VARCHAR(255) NULL DEFAULT NULL,
  `START_DATE` TIMESTAMP NULL DEFAULT NULL,
  `END_DATE` TIMESTAMP NULL DEFAULT NULL,
  `PRIORITY_ID` VARCHAR(255) NULL DEFAULT NULL,
  `PRICE_LIST_ID` INT NOT NULL AUTO_INCREMENT,
  `PRICE` FLOAT NULL DEFAULT NULL,
  `CURR` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`PRICE_LIST_ID`),
    FOREIGN KEY (`BRAND_ID`)
    REFERENCES `BRANDS` (`ID`),
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `PRODUCTS` (`ID`),
    FOREIGN KEY (`PRIORITY_ID`)
    REFERENCES `PRIORITY` (`ID`));



INSERT INTO BRANDS (NAME) VALUES
    ('Brand1'),
    ('Brand2'),
    ('Brand3');


    -- Insert data into the PRODUCTS table
    INSERT INTO `PRODUCTS` (`ID`, `NAME`, `DESCRIPTION`)
    VALUES ('35455', 'Product1', 'Description1'),
           ('35456', 'Product2', 'Description2'),
           ('35457', 'Product3', 'Description3');

    -- Insert data into the PRIORITY table
    INSERT INTO `PRIORITY` (`ID`, `NAME`)
    VALUES ('0', 'Priority1'),
           ('1', 'Priority2'),
           ('2', 'Priority3');


INSERT INTO PRICES (`BRAND_ID`,`PRODUCT_ID`,`START_DATE`,`END_DATE`,`PRIORITY_ID`,`PRICE_LIST_ID`,`PRICE`,`CURR`) VALUES (1,'35455','2020-06-14 00:00:00','2020-12-31 23:59:59','0',1,35.5,'EUR');
INSERT INTO PRICES (`BRAND_ID`,`PRODUCT_ID`,`START_DATE`,`END_DATE`,`PRIORITY_ID`,`PRICE_LIST_ID`,`PRICE`,`CURR`) VALUES (1,'35455','2020-06-14 15:00:00','2020-06-14 18:30:00','1',2,25.45,'EUR');
INSERT INTO PRICES (`BRAND_ID`,`PRODUCT_ID`,`START_DATE`,`END_DATE`,`PRIORITY_ID`,`PRICE_LIST_ID`,`PRICE`,`CURR`) VALUES (1,'35455','2020-06-15 00:00:00','2020-06-15 11:00:00','1',3,30.5,'EUR');
INSERT INTO PRICES (`BRAND_ID`,`PRODUCT_ID`,`START_DATE`,`END_DATE`,`PRIORITY_ID`,`PRICE_LIST_ID`,`PRICE`,`CURR`) VALUES (1,'35455','2020-06-15 16:00:00','2020-12-31 23:59:59','1',4,38.95,'EUR');




